from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from app.database import get_db
from app.models.ticket import Ticket, InputEvent
from app.models.report import Report
from pydantic import BaseModel
from app.agents.llm_client import generate_completion
import json

router = APIRouter()

class ChatRequest(BaseModel):
    message: str

@router.post("/ticket/{ticket_id}/chat")
def chat_with_copilot(ticket_id: int, request: ChatRequest, db: Session = Depends(get_db)):
    """
    AI Copilot Chat Endpoint.
    Contextualizes the LLM with the ticket details and all department reports, then answers the user's message.
    """
    ticket = db.query(Ticket).filter(Ticket.id == ticket_id).first()
    if not ticket:
        raise HTTPException(status_code=404, detail="Ticket not found")

    input_event = db.query(InputEvent).filter(InputEvent.ticket_id == ticket_id).first()
    event_details = input_event.payload.get("details", "") if input_event else "No details."

    reports = db.query(Report).filter(Report.ticket_id == ticket_id).all()
    reports_text = ""
    for r in reports:
        reports_text += f"\n--- {r.department_id} ---\n{json.dumps(r.content)}\n"

    system_prompt = """You are the Sentinels AI Risk Copilot.
You assist human Risk Managers by answering questions about specific risk tickets.
You have access to the original event details and the reports generated by various AI agents (including the Chief Risk Officer).
Be concise, helpful, and professional. Do not hallucinate data not in the ticket context.
"""

    prompt = f"""=== TICKET #{ticket_id} CONTEXT ===
Event Details: {event_details}

Department Reports:
{reports_text}
===

User Question: {request.message}
"""

    response_text = generate_completion(
        prompt=prompt,
        system_prompt=system_prompt,
        model="llama-3.3-70b-versatile",
        json_mode=False
    )

    return {"reply": response_text}
