from app.logger import logger
import io
import json
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT
from app.models.report import Report
from typing import List
from app.agents.llm_client import generate_completion

def generate_pdf_report(ticket_id: int, reports: List[Report]) -> bytes:
    buffer = io.BytesIO()
    
    # 1. Synthesize with AI
    if not reports:
        return _build_empty_pdf(buffer, ticket_id)
        
    reports_text = ""
    for r in reports:
        reports_text += f"Dept: {r.department_id}\nContent: {json.dumps(r.content)}\n\n"
        
    prompt = f"Ticket {ticket_id} Reports:\n{reports_text}\nProvide a unified executive summary."
    system_prompt = """You are an elite Executive AI Risk Analyst for Sentinels.
Synthesize the provided departmental reports into a highly professional executive summary.
Output pure JSON exactly with the following keys:
- "executive_summary": A strong, 3-4 sentence high-level overview.
- "key_risks": A list of strings, 3 concise bullet points outlining primary risks.
- "recommended_actions": A list of strings, 2-3 strategic recommendations.
- "global_risk_level": A single word indicating overall risk (e.g. LOW, MEDIUM, HIGH, CRITICAL).
"""
    
    try:
        response_text = generate_completion(
            prompt=prompt,
            system_prompt=system_prompt,
            model="llama-3.3-70b-versatile",
            json_mode=True
        )
        data = json.loads(response_text)
    except Exception as e:
        logger.info(f"[PDF Export] AI Synthesis failed: {e}")
        data = {
            "executive_summary": "Error generating AI summary. Fallback mode.",
            "key_risks": ["Unable to parse risks from agents."],
            "recommended_actions": ["Manual review required."],
            "global_risk_level": "UNKNOWN"
        }

    # 2. Build PDF Layout
    doc = SimpleDocTemplate(
        buffer, pagesize=letter,
        rightMargin=50, leftMargin=50,
        topMargin=50, bottomMargin=50
    )
    styles = getSampleStyleSheet()
    
    # Custom Brand Styles
    brand_blue = colors.HexColor("#0f172a") # Dark Slate
    brand_accent = colors.HexColor("#3b82f6") # Blue
    brand_green = colors.HexColor("#10b981") # Green
    brand_red = colors.HexColor("#ef4444") # Red
    
    risk_color = brand_green
    if data.get("global_risk_level", "").upper() in ["HIGH", "CRITICAL"]:
        risk_color = brand_red
    elif data.get("global_risk_level", "").upper() == "MEDIUM":
        risk_color = colors.orange

    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=24,
        textColor=brand_blue,
        alignment=TA_CENTER,
        spaceAfter=20
    )
    
    subtitle_style = ParagraphStyle(
        'SubtitleStyle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=12,
        textColor=colors.gray,
        alignment=TA_CENTER,
        spaceAfter=30
    )

    section_header = ParagraphStyle(
        'SectionHeader',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=14,
        textColor=brand_accent,
        spaceBefore=20,
        spaceAfter=10,
        borderPadding=(0, 0, 4, 0),
    )
    
    body_style = ParagraphStyle(
        'BodyStyle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=11,
        textColor=colors.black,
        leading=16,
        alignment=TA_JUSTIFY,
        spaceAfter=14
    )
    
    bullet_style = ParagraphStyle(
        'BulletStyle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=11,
        textColor=colors.black,
        leading=16,
        leftIndent=20,
        bulletIndent=10,
        spaceAfter=10
    )

    story = []
    
    # --- HEADER ---
    story.append(Paragraph("SENTINELS INTELLIGENCE PLATFORM", title_style))
    story.append(Paragraph("EXECUTIVE RISK ANALYSIS REPORT", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=brand_accent, spaceBefore=0, spaceAfter=20))
    
    # --- META INFO ---
    meta_data = [
        ["Ticket ID:", f"#{ticket_id}", "Global Risk:", data.get("global_risk_level", "N/A").upper()],
        ["Departments:", str(len(reports)), "Generated By:", "Sentinels AI Orchestrator"]
    ]
    t = Table(meta_data, colWidths=[80, 150, 80, 150])
    t.setStyle(TableStyle([
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica-Bold'),
        ('FONTNAME', (1,0), (1,-1), 'Helvetica'),
        ('FONTNAME', (3,0), (3,-1), 'Helvetica'),
        ('TEXTCOLOR', (3,0), (3,0), risk_color), # Risk color
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(t)
    story.append(Spacer(1, 20))
    
    # --- EXECUTIVE SUMMARY ---
    story.append(Paragraph("EXECUTIVE SUMMARY", section_header))
    story.append(Paragraph(data.get("executive_summary", "N/A"), body_style))
    
    # --- KEY RISKS ---
    story.append(Paragraph("KEY RISKS IDENTIFIED", section_header))
    for risk in data.get("key_risks", []):
        story.append(Paragraph(f"• {risk}", bullet_style))
        
    # --- RECOMMENDED ACTIONS ---
    story.append(Paragraph("RECOMMENDED ACTIONS", section_header))
    for action in data.get("recommended_actions", []):
        story.append(Paragraph(f"• {action}", bullet_style))
        
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey, spaceBefore=20, spaceAfter=20))
    
    # --- DEPARTMENTAL BREAKDOWN ---
    story.append(Paragraph("DEPARTMENTAL REPORT DATA", section_header))
    for r in reports:
        story.append(Paragraph(f"<b>{r.department_id}</b> (Status: {r.status})", body_style))
        
    # Build PDF
    doc.build(story)
    
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes

def _build_empty_pdf(buffer, ticket_id):
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    story = [Paragraph(f"No reports available for Ticket #{ticket_id}", getSampleStyleSheet()['Normal'])]
    doc.build(story)
    return buffer.getvalue()
